/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.isc.prog4.mvc.vista;

import co.edu.utp.isc.prog4.mvc.controlador.AgendaControlador;
import co.edu.utp.isc.prog4.mvc.modelo.Contacto;
import co.edu.utp.isc.prog4.mvc.modelo.Telefono;
import co.edu.utp.isc.prog4.mvc.modelo.TipoTelefono;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utp
 */
public class FrmAgenda extends javax.swing.JFrame implements FormularioVisitador {

    /**
     * Creates new form Fr
     */
    public FrmAgenda() {
        initComponents();
        iniciarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevoContacto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGuardarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        pnlCardTelefonos = new javax.swing.JPanel();
        pnlTelefonos = new co.edu.utp.isc.prog4.mvc.vista.PnlTelefonos();
        pnlNuevoTelefono = new co.edu.utp.isc.prog4.mvc.vista.PnlNuevoTelefono();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevoContacto.setText("Nuevo Contacto");
        btnNuevoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoContactoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoContacto);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 267));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnEliminar.setText("Eliminar");
        jPanel4.add(btnEliminar);

        btnGuardarArchivo.setText("Enviar Archivo");
        btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivoActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardarArchivo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Alias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblContactosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblContactos);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jLabel1.setText("Nombre");

        jLabel2.setText("Alias");

        pnlCardTelefonos.setLayout(new java.awt.CardLayout());
        pnlCardTelefonos.add(pnlTelefonos, "lista");
        pnlCardTelefonos.add(pnlNuevoTelefono, "formulario");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCardTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlias))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 201, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCardTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoContactoActionPerformed
        txtAlias.setText("");
        txtNombre.setText("");
        tblContactos.clearSelection();
        cambiarTarjeta("formulario");

        pnlTelefonos.limpiar();
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnNuevoContactoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String alias = txtAlias.getText().trim();
        List<Telefono> telefonos = pnlTelefonos.getLista();

        AgendaControlador.getInstance()
                .agregarContacto(tblContactos.getSelectedRow(),
                        nombre, alias, telefonos);
        cargarLista();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblContactosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContactosMouseReleased
        if(evt.getClickCount() >= 2){
            Contacto contacto = AgendaControlador.getInstance().getContacto(tblContactos.getSelectedRow());
            txtNombre.setText(contacto.getNombre());
            txtAlias.setText(contacto.getAlias());
            cambiarTarjeta("lista");
            pnlTelefonos.setLista(contacto.getTelefonos());
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_tblContactosMouseReleased

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
        AgendaControlador.getInstance().guardarContactosArchivo();
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmAgenda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JButton btnNuevoContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCardTelefonos;
    private co.edu.utp.isc.prog4.mvc.vista.PnlNuevoTelefono pnlNuevoTelefono;
    private co.edu.utp.isc.prog4.mvc.vista.PnlTelefonos pnlTelefonos;
    private javax.swing.JTable tblContactos;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void iniciarFormulario() {
        setSize(800, 600);
        setLocationRelativeTo(null);

        pnlTelefonos.setFormulario(this);
        pnlNuevoTelefono.setFormulario(this);

        cargarLista();
        btnNuevoContactoActionPerformed(null);
    }

    @Override
    public void cambiarTarjeta(String tarjeta) {
        if (tarjeta.equals("formulario")) {
            pnlNuevoTelefono.limpiarCampos();
        } else if (tarjeta.equals("lista")) {
            pnlTelefonos.cargarLista();
        }
        ((CardLayout) pnlCardTelefonos.getLayout()).show(pnlCardTelefonos, tarjeta);
    }

    @Override
    public void agregarTelefono(TipoTelefono tipoTelefono, String numero) {
        pnlTelefonos.agregarTelefono(tipoTelefono, numero);
    }

    private void cargarLista() {
        int numero = ((DefaultTableModel)tblContactos.getModel()).getRowCount();
        for (int i = 0; i < numero; i++) {
            ((DefaultTableModel)tblContactos.getModel()).removeRow(0);
        }
        
        List<Contacto> contactos = AgendaControlador.getInstance().getContactos();
        for (int i = 0; i < contactos.size(); i++) {
            ((DefaultTableModel)tblContactos.getModel()).addRow(new Object[]{
                contactos.get(i).getNombre(),
                contactos.get(i).getAlias()
            });
        }
    }
}
